### ISSUE TITLE
consider a different name

### ISSUE THREAD

**Issue by whit537** [AspenWeb/state_chain.py#3]
Algorithm is generic. @Changaco had some name for the pattern we're using, started with an em and came from functional programming.

**Comment by Changaco** [comment]
Other idea: function chains.

**Comment by whit537** [comment]
It's not really a pipeline because the output of one doesn't strictly become the input of the next. The output of one becomes part of the namespace available to the next.

**Comment by whit537** [comment]
I considered [daisy chain](https://en.wikipedia.org/wiki/Daisy_chain_(electrical_engineering)), but that's not really accurate for the same reason that `function chain` or `pipeline` isn't: the output of one function doesn't directly feed the next. Rather, the distinctive feature here is that all functions operate on a common state dictionary. For this reason, my current favorite option is `state_chain`.

**Comment by whit537** [comment]
("Function chains" call to mind jQuery and C#, where the term refers to `foo().bar().baz()`. That's not what we have here.)

**Comment by whit537** [comment]
I looked into [how Christmas lights are wired](v), because I had an inkling that it was perhaps close enough to our case to provide some inspiration. I didn't find that to be the case upon inspection, however.

**Comment by whit537** [comment]
My current proposal is `state_chain`.

**Comment by whit537** [comment]
@pjz free-associated https://en.wikipedia.org/wiki/Tuple_space.

**Comment by Changaco** [comment]
We've started using `state_chain` in Pando: <https://github.com/AspenWeb/pando.py/pull/573>.

**Comment by whit537** [comment]
`state_chain` it is!
