### ISSUE TITLE
implement error handling differently

### ISSUE THREAD

**Issue by chadwhitacre** [AspenWeb/state_chain.py#4]
Error handling as currently implemented is not entirely intuitive. Essentially we're folding a branching tree into a linear flow, and it's hard to reason about that. What if instead we provided for a list of lists?

``` python
normal = [foo, bar, baz, buz]
fallback = [blah, buz]
last_ditch = [bloo]

algo = Algorithm(*normal, _cascade=[fallback, last_ditch])
```

**Comment by Changaco** [comment]
I don't think it's a good idea to implement “sub-chains”. It would significantly complicate many things.
