### ISSUE TITLE
require explicit skips when assigning to .functions

### ISSUE THREAD

**Issue by Changaco** [AspenWeb/state_chain.py#5]
In Gratipay we patch Aspen's website algorithm [by setting `algorithm.functions`](https://github.com/gratipay/gratipay.com/blob/1792/gratipay/main.py#L84-124). This method implicitly skips functions, so [when a function is added to the algorithm upstream](https://github.com/gratipay/aspen-python/issues/422) and we don't notice the change or forget to propagate it, then we can end up with silent errors like https://github.com/gratipay/gratipay.com/issues/3210.

A method of modifying the algorithm based on **explicit** skipping would fix the silent error problem.

**Comment by whit537** [comment]
For reference, here are the docs on [Modifying an Algorithm](http://algorithm-py.readthedocs.org/en/1.0.0/#modifying-an-algorithm). It's possible to explicitly modify an algorithm using `insert_{before,after}` and `remove`. That method seemed to me to have the tendency to result in insufficient control over the final algorithm definition, hence the practice of overriding the algorithm definition to explicitly include functions from the underlying algorithm. I agree that errors such as we experienced on gratipay/gratipay.com#3210 are a weak point of this approach.

**Comment by whit537** [comment]
If we use `insert_{before,after}` and `remove` then we lose the clarity of having all of the functions in a single list. It would be harder to visualize what exactly an algorithm is doing.

**Comment by Changaco** [comment]
What I'm proposing here is a method where you both see the entire algorithm (unlike insert/remove) and have to explicitly skip functions (unlike setting `.functions`).

**Comment by whit537** [comment]
What if we raised an error at runtime if an algorithm didn't include all of its original functions, with a mechanism to override? A sketch:

```python
from algorithm import Algorithm

foo = lambda a: a
bar = lambda a: a
baz = lambda a: a

blah = Algorithm(foo, bar) 
blah.functions = [blah['foo'], baz]
blah.skip = [bar]
```

**Comment by Changaco** [comment]
I think raising an error when the algorithm is modified would be better. For example we could turn `.functions` into a property with a validating setter.

**Comment by whit537** [comment]
... and we could require that `blah.skip` be set prior to setting `blah.functions`. wfm

**Comment by Changaco** [comment]
What happens if you add in the `.functions` list a function that you've added to `.skip` ? I think a single source of truth would be better, something like:

```python
from algorithm import Algorithm, skip

foo = lambda a: a
bar = lambda a: a
baz = lambda a: a

blah = Algorithm(foo, bar) 
blah.functions = [blah['foo'], skip(blah['bar']), baz]
```

**Comment by whit537** [comment]
+1

**Comment by whit537** [comment]
+1 from @pjz at https://www.youtube.com/watch?v=xJPfikZXhQ0#t=1h09m50s. :)

**Comment by whit537** [comment]
Ftr we spent the [March 2015 Aspen call](https://www.youtube.com/watch?v=xJPfikZXhQ0) discussing this issue. For comparison, we [reimplemented the Gratipay algorithm using `insert_{before,after}`](https://gist.github.com/whit537/9eb3a29eb3a39753e30d), which gave rise to #6 and #7. This ticket still stands.

**Comment by pjz** [comment]
So to be clear, the desired spec is to make a .function property-setter that makes sure that the new value is a superset of (current .functions + .skip) ?  And if not, raise some kind of InvalidArgument or something?

**Comment by Changaco** [comment]
I don't think we want a `.skip` at all. The idea is to turn `.functions` into a setter that checks that the new list is a superset of the current one, I don't see why we'd need a `.skip` to implement that.

**Comment by pjz** [comment]
`.skip` is to allow non-error non-supersets iff the removed function(s) are in `.skip`.  So the new `.functions` has to be a supersets of (old `.functions` - `.skip`)
